spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/movies

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: posters/
  refreshTokenValidity: 24*60*60

base:
  url: "http://localhost:8080"